"""Keeps the standalone web chart in sync with the benchmark export."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable


CHART_FILENAME = "high_value_subscriptions_tasks_per_dollar.html"
DATA_MARKER = '<script id="benchmark-data" type="application/json">'
SCRIPT_END = "</script>"


def get_repo_root() -> Path:
    """Return the repository root containing the benchmark sources."""
    return Path(__file__).resolve().parent.parent


def update_chart_html(
    rows: Iterable[dict[str, Any]],
    output_path: str | Path | None = None,
) -> Path:
    """Inject the latest benchmark rows into the standalone chart HTML.

    The HTML owns layout, interaction, and export behavior. This function only
    replaces its embedded data payload so the chart remains offline-capable and
    never drifts from the CSV/JSON exports generated by the same run.
    """
    chart_path = Path(output_path) if output_path else get_repo_root() / "charts" / CHART_FILENAME
    html = chart_path.read_text(encoding="utf-8")

    marker_start = html.find(DATA_MARKER)
    if marker_start < 0:
        raise ValueError(f"Chart HTML is missing the data marker: {DATA_MARKER}")
    payload_start = marker_start + len(DATA_MARKER)
    payload_end = html.find(SCRIPT_END, payload_start)
    if payload_end < 0:
        raise ValueError("Chart HTML data marker is missing its closing script tag")

    payload = json.dumps(list(rows), ensure_ascii=False, separators=(",", ":"))
    updated = html[:payload_start] + "\n" + payload + "\n  " + html[payload_end:]
    chart_path.write_text(updated, encoding="utf-8")
    return chart_path
